### ISSUE TITLE
1.1.0 umbrella issue

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#393]
This issue tracks the tasks needed for 1.1.0 version:

## CLI features

  * [x] add a `--confirm yes` flag to `reset` subcommand (#392)
  * [x] support for multiple execution environments (#213)
  * [x] support for arbitrary execution environments, not just the ones in our docker hub (#307)
  * [x] `require` for env variables (#371).
  * [x] matrix execution (#362)
  * [x] support for Jenkins (#130)

## docs

  * new reorganized docs/ folder (#355)
      * cli features
          * [x] search and import
          * [x] visualizing a pipeline
          * [x] adding metadata to a project
          * [x] archiving a project and obtaining DOIs
      * other resources
          * [x] automated artifact evaluation
  * new CI section
      * [ ] describe environments
      * [ ] describe list of executions
      * [x] describe how matrix execution works
  * landing page updates:
      * [ ] update screencast on landing page
      * [x] update links
  * update README
      * [x] add logo
      * [x] update links

## Example pipelines

  * [x] GCE
  * [x] Chameleon
  * [x] CloudLab

## Blog
  * [x] Create schedule for weekly posts
